name: load_more_flutter
description: Load more data when scroll to end of ListView Flutter.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.16.0

  distinct_value_connectable_stream: ^1.1.1
  rxdart: ^0.24.1
  rx_redux: ^2.1.0
  disposebag: ^1.2.0

  collection: ^1.14.13
  tuple: ^2.0.0
  built_value: ^7.1.0
  built_collection: ^4.3.2
  cached_network_image: ^2.3.1
  http: ^0.13.0

#flutter packages pub run build_runner build

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/people.json
flutter_intl:
  enabled: true
